version = 1

exclude_patterns = ["foo.py", "foo/bar*.py", "baz.py"]
test_patterns = ["tests/*"]

[[analyzers]]
  name = "python"
  enabled  = true
  dependency_file_paths = ["requirements.txt"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/deepsourcelabs/july"
  skip_doc_coverage = ["file"]
